"""empty message

Revision ID: 2daf291faa91
Revises: c981380d24be
Create Date: 2020-10-20 17:30:18.890724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2daf291faa91'
down_revision = 'c981380d24be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.add_column('Shows', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('Shows', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.drop_constraint('Shows_venueId_fkey', 'Shows', type_='foreignkey')
    op.drop_constraint('Shows_artistId_fkey', 'Shows', type_='foreignkey')
    op.create_foreign_key(None, 'Shows', 'Venue', ['venue_id'], ['id'])
    op.create_foreign_key(None, 'Shows', 'Artist', ['artist_id'], ['id'])
    op.drop_column('Shows', 'artistId')
    op.drop_column('Shows', 'showTime')
    op.drop_column('Shows', 'venueId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shows', sa.Column('venueId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Shows', sa.Column('showTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('Shows', sa.Column('artistId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Shows', type_='foreignkey')
    op.drop_constraint(None, 'Shows', type_='foreignkey')
    op.create_foreign_key('Shows_artistId_fkey', 'Shows', 'Artist', ['artistId'], ['id'])
    op.create_foreign_key('Shows_venueId_fkey', 'Shows', 'Venue', ['venueId'], ['id'])
    op.drop_column('Shows', 'venue_id')
    op.drop_column('Shows', 'start_time')
    op.drop_column('Shows', 'artist_id')
    # ### end Alembic commands ###
