"""empty message

Revision ID: 5e5a0bc2e72c
Revises: bfe91d0e1b48
Create Date: 2020-10-19 23:48:13.802386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5a0bc2e72c'
down_revision = 'bfe91d0e1b48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres_list', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('Artist', 'genres')
    op.add_column('Venue', sa.Column('genres_list', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'genres_list')
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'genres_list')
    # ### end Alembic commands ###
